### ISSUE TITLE
After an insert in the database, the app crashes

### ISSUE THREAD

**Issue by betacar** [pcel/meteor-mysql#2]
Here is the error stack trace:
````
W20151012-12:18:23.162(-7)? (STDERR) TypeError: Object 319 has no method 'apply'
W20151012-12:18:23.163(-7)? (STDERR)     at Query.Sequence.end (/Users/betacar/.meteor/packages/pcel_mysql/.0.1.0.1cu9u51++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
W20151012-12:18:23.163(-7)? (STDERR)     at Query.ErrorPacket (/Users/betacar/.meteor/packages/pcel_mysql/.0.1.0.1cu9u51++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/sequences/Query.js:93:8)
W20151012-12:18:23.163(-7)? (STDERR)     at Protocol._parsePacket (/Users/betacar/.meteor/packages/pcel_mysql/.0.1.0.1cu9u51++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Protocol.js:270:23)
W20151012-12:18:23.163(-7)? (STDERR)     at Parser.write (/Users/betacar/.meteor/packages/pcel_mysql/.0.1.0.1cu9u51++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Parser.js:77:12)
W20151012-12:18:23.163(-7)? (STDERR)     at Protocol.write (/Users/betacar/.meteor/packages/pcel_mysql/.0.1.0.1cu9u51++os+web.browser+web.cordova/npm/node_modules/mysql/lib/protocol/Protocol.js:39:16)
W20151012-12:18:23.163(-7)? (STDERR)     at Socket.<anonymous> (/Users/betacar/.meteor/packages/pcel_mysql/.0.1.0.1cu9u51++os+web.browser+web.cordova/npm/node_modules/mysql/lib/Connection.js:82:28)
W20151012-12:18:23.163(-7)? (STDERR)     at Socket.emit (events.js:95:17)
W20151012-12:18:23.163(-7)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20151012-12:18:23.163(-7)? (STDERR)     at Socket.emit (events.js:92:17)
W20151012-12:18:23.164(-7)? (STDERR)     at emitReadable_ (_stream_readable.js:427:10)
````

**Comment by betacar** [comment]
Solved by sending an array instead of arguments
